project:
  type: website
  output-dir: _site

website:
      title: "py-mealdb"
      site-url: https://kapitan.net
      search:
          location: sidebar
      sidebar:
          style: docked  
          collapse-level: 1
          background: '#008080'
          tools:
            - icon: github
              href: https://github.com/Sherwin-14/py-mealdb
          contents:
            - section: "API Reference"
              contents: about.qmd
quartodoc:
      package: quartodoc
      sections:
        - title: Some functions
          desc: Functions to inspect docstrings.
          contents:
            # the functions being documented in the package.
            # you can refer to anything: class methods, modules, etc..
            - get_object
            - preview

format:
  html:
    theme: darkly
    css: styles.css



