project:
  type: website
  output-dir: ./docs

website:
      title: "py-mealdb"
      sidebar:
          style: docked  
          background: '#008080'
          tools:
            - icon: github
              href: https://github.com/Sherwin-14/py-mealdb
          contents:
            - text: "Home" 
              href: index.qmd
            - text: "API Reference"
              href: reference/index.qmd.qmd
            - text: "Contributing Guide"
              href: contributing.qmd
quartodoc:
      style: pkgdown
      dir: reference
      package: py_mealdb
      dynamic: true
      parser: google
      sections:
      - title: MealDB API Client
        desc: Main client for interacting with TheMealDB API.
        contents:
          - name: MealDB
            children: separate
      
      - title: Data Models
        desc: Data structures for API responses.
        contents:
          - name: models.BaseList
            children: separate
          - name: models.MealList
            children: separate
          - name: models.MealDetails
            children: separate
          - name: models.AreaList
            children: separate
          - name: models.CategoryList
            children: separate
          - name: models.IngredientList
            children: separate
      

format:
  html:
    grid: 
      body-width: 1200px
    theme: journal
    css: styles.scss
    page_layout: full




