project:
  type: website
  output-dir: _site

website:
      title: "py-mealdb"
      site-url: https://kapitan.net
      sidebar:
          style: docked  
          background: '#008080'
          tools:
            - icon: github
              href: https://github.com/Sherwin-14/py-mealdb
          contents:
            - text: "Home" 
              href: index.qmd
            - text: "API Reference"
              href: about.qmd
            - text: "Contributing Guide"
              href: contributing.qmd
quartodoc:
      style: pkgdown
      dir: about.md
      package: ./mealdb.__init__.py
      sections:
        - title: 
          desc: Functions to inspect docstrings.
          contents:
            - get_meal_by_name
            - meal_details_by_id
            - single_random_meal
            - list_all_meals
            - list_meal_categories
            - list_all_categories
            - list_all_areas
            - list_all_ingredients
            - list_all
            - filter_by_ingredient
            - filter_by_category
            - filter_by_area

format:
  html:
    theme: darkly
    css: styles.scss




